### ISSUE TITLE
Pillow deprecated `textsize()` method

### ISSUE THREAD

**Issue by joamag** [hivesolutions/colony-plugins#14]
## Description

Pillow has just removed `textsize()` method in its latest version, effectively breaking compatibility with the part of colony-plugins.

## Solution

An alternative way must be found to calculate the width and height of a certain text.

A reference implementation exists [here](https://stackoverflow.com/a/77749307/476782).

Using https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textlength.

**Comment by joamag** [comment]
CC @hugo-gomes

**Comment by hugo-gomes** [comment]
For reference, here's a link to the implementation being replaced
* https://github.com/python-pillow/Pillow/blob/204590600c6a8c5246d0564d3312abd6e6b0ed70/src/PIL/ImageDraw.py#L648

And both replacements:
* https://github.com/python-pillow/Pillow/blob/204590600c6a8c5246d0564d3312abd6e6b0ed70/src/PIL/ImageDraw.py#L751
* https://github.com/python-pillow/Pillow/blob/204590600c6a8c5246d0564d3312abd6e6b0ed70/src/PIL/ImageDraw.py#L714

The new replacements do not return the same results:
`textsize()`: returns the width and height of the text
`textbbox()` returns the text's bounding box (which includes the coordinates of the top-left and bottom-right corners)
`textlength()`: returns the width of the text string in pixels

Determining which one to use will depend on whether the `textsize()` usage needs the size of the text or its position - this should be the deciding factor whether or not you should use a `textbox()`, `textlength()`, or both.

As a last resort, recovering `textsize()` implementation could also be an option. The method has some issues which seem to not be felt on colony-plugins.
